apiVersion: v1
kind: Service
metadata:
  name: news-summarizer-service
spec:
  type: LoadBalancer
  selector:
    app: news-summarizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
